### ISSUE TITLE
Issue while executing VSLAM node

### ISSUE THREAD

**Issue by rafism1997** [NVIDIA-ISAAC-ROS/.github#20] opened 2023-01-24 01:03 UTC
Hi Team, 

We are experiencing some issue while executing the vslam node : 

``` ros2 launch nvblox_examples_bringup nvblox_vslam_realsense.launch.py ```

Exact error is : 

```
[component_container-3] Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container-3]          at line 93 in /opt/ros/humble/src/geometry2/tf2/src/buffer_core.cpp
```
![vslamissue](https://user-images.githubusercontent.com/33804907/214191814-476f7f31-cafe-4fa9-bdd4-4f075244832a.png)

**Comment by hemalshahNV** [comment] 2023-01-30 23:38
Duplicate of https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/issues/52

**Closed as completed by hemalshahNV** 2023-01-30 23:38 UTC
Labels: duplicate
